MediManage/
├─ index.html                  (Home page)
├─ medications.html            (Medications page)
├─ add-medication.html         (Add New Medication page)
├─ appointments.html           (Appointments page)
├─ schedule-appointment.html   (Schedule New Appointment page)
├─ messages.html               (Messages page)
├─ new-message.html            (New Message page)
├─ styles.css                  (Shared CSS)
└─ scripts.js                  (Optional JavaScript)
